"""config: quem alterou e quando

Revision ID: 0234eadb1702
Revises: ebca27955309
Create Date: 2026-08-17 16:46:25.166458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0234eadb1702'
down_revision: Union[str, Sequence[str], None] = 'ebca27955309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacaoconfig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atualizado_por_nome', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('atualizado_por_email', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacaoconfig', schema=None) as batch_op:
        batch_op.drop_column('atualizado_por_email')
        batch_op.drop_column('atualizado_por_nome')

    # ### end Alembic commands ###
