"""prioridade importante e urgente_semantico persistido

Revision ID: 02ebad27db2f
Revises: 63a5dd0c8c12
Create Date: 2026-08-14 18:01:32.084596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '02ebad27db2f'
down_revision: Union[str, Sequence[str], None] = '63a5dd0c8c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Revisada: o `server_default=false` das duas colunas é o que permite
    acrescentá-las como NOT NULL numa tabela que já tem linhas. Sem ele o
    PostgreSQL recusaria, porque as linhas existentes ficariam sem valor.

    As linhas antigas nascem com `importante=false`, o que é o comportamento
    de antes desta mudança e não uma afirmação sobre elas. Salvar a
    configuração no painel roda `recalcular_urgencia`, que reclassifica as duas
    faixas a partir do prazo já guardado, sem gastar token nenhum.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailclassificado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importante', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('urgente_semantico', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index(batch_op.f('ix_emailclassificado_importante'), ['importante'], unique=False)

    # ### end Alembic commands ###

    # Backfill do sinal semântico, acrescentado à mão.
    #
    # Não é chute: pela regra ANTERIOR, um e-mail só podia estar urgente sem
    # prazo nenhum quando o modelo tinha marcado `urgente_semantico`. A coluna
    # não existia, mas a informação estava implícita nessa combinação, e isto a
    # reconstrói exatamente.
    #
    # Sem o backfill, o primeiro `recalcular_urgencia` (que dispara ao salvar a
    # configuração no painel) desmarcaria em silêncio todo e-mail urgente por
    # sinal semântico, porque a coluna nova nasceria `false` para eles.
    op.execute(
        "UPDATE emailclassificado SET urgente_semantico = true "
        "WHERE urgente = true AND urgencia_prazo_horas IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailclassificado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emailclassificado_importante'))
        batch_op.drop_column('urgente_semantico')
        batch_op.drop_column('importante')

    # ### end Alembic commands ###
