"""converte para o agente de suporte ao comercial

Revision ID: 63a5dd0c8c12
Revises: 6d498222ebee
Create Date: 2026-08-07 16:38:06.978032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '63a5dd0c8c12'
down_revision: Union[str, Sequence[str], None] = '6d498222ebee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classificacaoconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('horario_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('horario_2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('janela_urgencia_horas', sa.Integer(), nullable=False),
    sa.Column('lookback_horas', sa.Integer(), nullable=False),
    sa.Column('max_emails_por_execucao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultima_execucao_agendada', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classificacaoconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classificacaoconfig_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('classificacaorun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_emails', sa.Integer(), nullable=False),
    sa.Column('processados', sa.Integer(), nullable=False),
    sa.Column('classificados', sa.Integer(), nullable=False),
    sa.Column('ignorados', sa.Integer(), nullable=False),
    sa.Column('urgentes', sa.Integer(), nullable=False),
    sa.Column('resumidos', sa.Integer(), nullable=False),
    sa.Column('puladas', sa.Integer(), nullable=False),
    sa.Column('falhas', sa.Integer(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('avisos', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duracao_segundos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classificacaorun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classificacaorun_duracao_segundos'), ['duracao_segundos'], unique=False)
        batch_op.create_index(batch_op.f('ix_classificacaorun_origem'), ['origem'], unique=False)
        batch_op.create_index(batch_op.f('ix_classificacaorun_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_classificacaorun_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_classificacaorun_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classificacaorun_user_email'), ['user_email'], unique=False)

    op.create_table('pastaclasse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('classe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pasta_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pasta_caminho', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pasta_id', sa.Text(), nullable=True),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.Column('erro_resolucao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'classe', name='uq_pasta_tenant_classe')
    )
    with op.batch_alter_table('pastaclasse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pastaclasse_classe'), ['classe'], unique=False)
        batch_op.create_index(batch_op.f('ix_pastaclasse_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('emailclassificado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('internet_message_id', sqlmodel.sql.sqltypes.AutoString(length=998), nullable=False),
    sa.Column('graph_message_id', sa.Text(), nullable=True),
    sa.Column('graph_conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('graph_web_link', sa.Text(), nullable=True),
    sa.Column('remetente_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remetente_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('corpo_texto', sa.Text(), nullable=True),
    sa.Column('recebido_em', sa.DateTime(), nullable=False),
    sa.Column('classe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urgente', sa.Boolean(), nullable=False),
    sa.Column('urgencia_prazo_horas', sa.Integer(), nullable=True),
    sa.Column('confianca', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria_aplicada', sa.Boolean(), nullable=False),
    sa.Column('movido', sa.Boolean(), nullable=False),
    sa.Column('pasta_destino_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('classificado_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['classificacaorun.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'internet_message_id', name='uq_email_tenant_imid')
    )
    with op.batch_alter_table('emailclassificado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emailclassificado_classe'), ['classe'], unique=False)
        batch_op.create_index(batch_op.f('ix_emailclassificado_graph_conversation_id'), ['graph_conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emailclassificado_internet_message_id'), ['internet_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emailclassificado_recebido_em'), ['recebido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_emailclassificado_remetente_email'), ['remetente_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_emailclassificado_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emailclassificado_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_emailclassificado_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emailclassificado_urgente'), ['urgente'], unique=False)

    op.create_table('resumoemail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('pontos_chave', sa.Text(), nullable=True),
    sa.Column('acao_sugerida', sa.Text(), nullable=True),
    sa.Column('prazo_mencionado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gerado_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emailclassificado.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumoemail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumoemail_email_id'), ['email_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_resumoemail_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumoemail_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('companycontact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companycontact_company_id'))
        batch_op.drop_index(batch_op.f('ix_companycontact_tenant_id'))

    op.drop_table('companycontact')
    with op.batch_alter_table('hunteraccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hunteraccount_slot'))

    op.drop_table('hunteraccount')
    with op.batch_alter_table('priorizacaorun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priorizacaorun_search_run_id'))
        batch_op.drop_index(batch_op.f('ix_priorizacaorun_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_priorizacaorun_user_email'))

    op.drop_table('priorizacaorun')
    with op.batch_alter_table('enrichmentrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichmentrun_search_run_id'))
        batch_op.drop_index(batch_op.f('ix_enrichmentrun_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_enrichmentrun_user_email'))

    op.drop_table('enrichmentrun')
    with op.batch_alter_table('searchconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searchconfig_tenant_id'))

    op.drop_table('searchconfig')
    with op.batch_alter_table('hunterusage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hunterusage_account_slot'))
        batch_op.drop_index(batch_op.f('ix_hunterusage_contact_id'))
        batch_op.drop_index(batch_op.f('ix_hunterusage_created_at'))
        batch_op.drop_index(batch_op.f('ix_hunterusage_tenant_id'))

    op.drop_table('hunterusage')
    op.drop_table('product')

    # ORDEM CORRIGIDA À MÃO. O autogenerate emitiu `searchrun` ANTES de
    # `prospectcompany`, e o PostgreSQL recusou: `prospectcompany` tem uma chave
    # estrangeira apontando para `searchrun`, então a tabela referenciada não
    # pode sair primeiro. O alembic não ordena drops por dependência; quem
    # ordena é quem revisa. Trocar a ordem é preferível a usar CASCADE, que
    # derrubaria em silêncio qualquer outro dependente que aparecesse.
    with op.batch_alter_table('prospectcompany', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospectcompany_alerta_situacao'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_approach_status'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_cnpj'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_dominio'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_enrichment_status'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_priorizacao_status'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_search_run_id'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_user_email'))

    op.drop_table('prospectcompany')
    with op.batch_alter_table('searchrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searchrun_pesquisa_id'))
        batch_op.drop_index(batch_op.f('ix_searchrun_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_searchrun_user_email'))

    op.drop_table('searchrun')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_tenant_id'))

    op.drop_table('lead')
    with op.batch_alter_table('kipflowusage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kipflowusage_tenant_id'))

    op.drop_table('kipflowusage')
    with op.batch_alter_table('integrationsetting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_pasta_origem', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'inbox'"), nullable=False))
        batch_op.drop_column('kipflow_base_url')
        batch_op.drop_column('hunter_dia_renovacao')
        batch_op.drop_column('kipflow_api_key_enc')
        batch_op.drop_column('hunter_creditos_mensais')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrationsetting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hunter_creditos_mensais', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('kipflow_api_key_enc', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hunter_dia_renovacao', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('kipflow_base_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('graph_pasta_origem')

    op.create_table('kipflowusage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('kipflowusage_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kipflowusage_pkey'))
    )
    with op.batch_alter_table('kipflowusage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kipflowusage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lead',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('lead_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lead_pkey'))
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('prospectcompany',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('localizacao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('segmento_identificado', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('icp_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('justificativa_match', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dominio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('razao_social', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('data_inicio_atividade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idade_empresa_anos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('porte', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('porte_original', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('segmento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('faturamento_estimado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_cadastral', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_cadastral_original', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alerta_situacao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alerta_situacao_desde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website_principal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefone_whatsapp', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enrichment_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('enrichment_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enriched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enrichment_errors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kipflow_raw_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kipflow_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('priorizacao_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priorizacao_score_final', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priorizacao_classe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priorizacao_criterios', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priorizacao_executado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('priorizacao_erro', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('approach_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('approach_dicas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approach_executado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approach_erro', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['searchrun.id'], name=op.f('prospectcompany_search_run_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('prospectcompany_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prospectcompany_pkey'))
    )
    with op.batch_alter_table('prospectcompany', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospectcompany_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_search_run_id'), ['search_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_priorizacao_status'), ['priorizacao_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_enrichment_status'), ['enrichment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_dominio'), ['dominio'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_cnpj'), ['cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_approach_status'), ['approach_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_alerta_situacao'), ['alerta_situacao'], unique=False)

    op.create_table('searchrun',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pesquisa_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('regiao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('segmento', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_empresas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meta_atingida', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('resumo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('erro', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('result_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('searchrun_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('searchrun_pkey'))
    )
    with op.batch_alter_table('searchrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searchrun_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_searchrun_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_searchrun_pesquisa_id'), ['pesquisa_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('product_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_pkey'))
    )
    op.create_table('hunterusage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dominio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('encontrado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('creditos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_slot', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('hunterusage_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hunterusage_pkey'))
    )
    with op.batch_alter_table('hunterusage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hunterusage_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hunterusage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hunterusage_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hunterusage_account_slot'), ['account_slot'], unique=False)

    op.create_table('searchconfig',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_ids', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('regiao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('segmento', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_search_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('searchconfig_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('searchconfig_pkey'))
    )
    with op.batch_alter_table('searchconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searchconfig_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('enrichmentrun',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('search_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_empresas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processadas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('puladas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('falhas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custo_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('erro', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('avisos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['search_run_id'], ['searchrun.id'], name=op.f('enrichmentrun_search_run_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('enrichmentrun_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('enrichmentrun_pkey'))
    )
    with op.batch_alter_table('enrichmentrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichmentrun_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichmentrun_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichmentrun_search_run_id'), ['search_run_id'], unique=False)

    op.create_table('priorizacaorun',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('search_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('incluiu_approach', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('total_leads', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processados', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('puladas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('falhas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('erro', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('avisos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['search_run_id'], ['searchrun.id'], name=op.f('priorizacaorun_search_run_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('priorizacaorun_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('priorizacaorun_pkey'))
    )
    with op.batch_alter_table('priorizacaorun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priorizacaorun_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_priorizacaorun_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_priorizacaorun_search_run_id'), ['search_run_id'], unique=False)

    op.create_table('hunteraccount',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slot', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('api_key_enc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hunteraccount_pkey'))
    )
    with op.batch_alter_table('hunteraccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hunteraccount_slot'), ['slot'], unique=True)

    op.create_table('companycontact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cargo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('senioridade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('perfil_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('perfil_public_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origem', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_confianca', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email_buscado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['prospectcompany.id'], name=op.f('companycontact_company_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('companycontact_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('companycontact_pkey'))
    )
    with op.batch_alter_table('companycontact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companycontact_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companycontact_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('resumoemail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumoemail_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_resumoemail_status'))
        batch_op.drop_index(batch_op.f('ix_resumoemail_email_id'))

    op.drop_table('resumoemail')
    with op.batch_alter_table('emailclassificado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emailclassificado_urgente'))
        batch_op.drop_index(batch_op.f('ix_emailclassificado_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_emailclassificado_status'))
        batch_op.drop_index(batch_op.f('ix_emailclassificado_run_id'))
        batch_op.drop_index(batch_op.f('ix_emailclassificado_remetente_email'))
        batch_op.drop_index(batch_op.f('ix_emailclassificado_recebido_em'))
        batch_op.drop_index(batch_op.f('ix_emailclassificado_internet_message_id'))
        batch_op.drop_index(batch_op.f('ix_emailclassificado_graph_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_emailclassificado_classe'))

    op.drop_table('emailclassificado')
    with op.batch_alter_table('pastaclasse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pastaclasse_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pastaclasse_classe'))

    op.drop_table('pastaclasse')
    with op.batch_alter_table('classificacaorun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classificacaorun_user_email'))
        batch_op.drop_index(batch_op.f('ix_classificacaorun_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_classificacaorun_status'))
        batch_op.drop_index(batch_op.f('ix_classificacaorun_started_at'))
        batch_op.drop_index(batch_op.f('ix_classificacaorun_origem'))
        batch_op.drop_index(batch_op.f('ix_classificacaorun_duracao_segundos'))

    op.drop_table('classificacaorun')
    with op.batch_alter_table('classificacaoconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classificacaoconfig_tenant_id'))

    op.drop_table('classificacaoconfig')
    # ### end Alembic commands ###
