"""baseline: schema da plataforma de prospeccao

Primeira migration do projeto. Ate aqui o schema nunca foi versionado: as
tabelas eram criadas direto pelo SQLModel. Esta revisao congela o estado de
origem para que a conversao para o Agente de Suporte ao Comercial, na
revisao seguinte, seja um passo reversivel e nao uma reconstrucao do zero.

Revision ID: 6d498222ebee
Revises: 
Create Date: 2026-08-07 15:21:21.407897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6d498222ebee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentmodelsetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effort', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agentmodelsetting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agentmodelsetting_agent_key'), ['agent_key'], unique=True)

    op.create_table('hunteraccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hunteraccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hunteraccount_slot'), ['slot'], unique=True)

    op.create_table('integrationsetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_sender_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('graph_tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('graph_client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('graph_client_secret_enc', sa.Text(), nullable=True),
    sa.Column('kipflow_api_key_enc', sa.Text(), nullable=True),
    sa.Column('kipflow_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hunter_creditos_mensais', sa.Integer(), nullable=False),
    sa.Column('hunter_dia_renovacao', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokenpricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_cost_per_token', sa.Float(), nullable=False),
    sa.Column('output_cost_per_token', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokenpricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokenpricing_model'), ['model'], unique=True)

    op.create_table('activitylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activitylog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activitylog_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmessage_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessage_user_email'), ['user_email'], unique=False)

    op.create_table('hunterusage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('dominio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encontrado', sa.Boolean(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('account_slot', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hunterusage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hunterusage_account_slot'), ['account_slot'], unique=False)
        batch_op.create_index(batch_op.f('ix_hunterusage_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hunterusage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hunterusage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('kipflowusage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kipflowusage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kipflowusage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('regiao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segmento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_search_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('searchconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searchconfig_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('searchrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pesquisa_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('regiao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segmento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_empresas', sa.Integer(), nullable=False),
    sa.Column('meta_atingida', sa.Boolean(), nullable=False),
    sa.Column('resumo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('erro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('searchrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searchrun_pesquisa_id'), ['pesquisa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_searchrun_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_searchrun_user_email'), ['user_email'], unique=False)

    op.create_table('tokenusage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokenusage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokenusage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokenusage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_reset_token'), ['reset_token'], unique=False)

    op.create_table('enrichmentrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_empresas', sa.Integer(), nullable=False),
    sa.Column('processadas', sa.Integer(), nullable=False),
    sa.Column('puladas', sa.Integer(), nullable=False),
    sa.Column('falhas', sa.Integer(), nullable=False),
    sa.Column('custo_total', sa.Float(), nullable=False),
    sa.Column('erro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avisos', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_run_id'], ['searchrun.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichmentrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichmentrun_search_run_id'), ['search_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichmentrun_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichmentrun_user_email'), ['user_email'], unique=False)

    op.create_table('priorizacaorun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incluiu_approach', sa.Boolean(), nullable=False),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('processados', sa.Integer(), nullable=False),
    sa.Column('puladas', sa.Integer(), nullable=False),
    sa.Column('falhas', sa.Integer(), nullable=False),
    sa.Column('erro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avisos', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_run_id'], ['searchrun.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('priorizacaorun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priorizacaorun_search_run_id'), ['search_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_priorizacaorun_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_priorizacaorun_user_email'), ['user_email'], unique=False)

    op.create_table('prospectcompany',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('localizacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segmento_identificado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icp_score', sa.Integer(), nullable=False),
    sa.Column('justificativa_match', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dominio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('razao_social', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('data_inicio_atividade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idade_empresa_anos', sa.Integer(), nullable=True),
    sa.Column('porte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('porte_original', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('segmento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('faturamento_estimado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_cadastral', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_cadastral_original', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alerta_situacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alerta_situacao_desde', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_principal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefone_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enrichment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enrichment_percentage', sa.Integer(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('enrichment_errors', sa.Text(), nullable=True),
    sa.Column('kipflow_raw_response', sa.Text(), nullable=True),
    sa.Column('kipflow_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('priorizacao_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priorizacao_score_final', sa.Integer(), nullable=True),
    sa.Column('priorizacao_classe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priorizacao_criterios', sa.Text(), nullable=True),
    sa.Column('priorizacao_executado_em', sa.DateTime(), nullable=True),
    sa.Column('priorizacao_erro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approach_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approach_dicas', sa.Text(), nullable=True),
    sa.Column('approach_executado_em', sa.DateTime(), nullable=True),
    sa.Column('approach_erro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['searchrun.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prospectcompany', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospectcompany_alerta_situacao'), ['alerta_situacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_approach_status'), ['approach_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_cnpj'), ['cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_dominio'), ['dominio'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_enrichment_status'), ['enrichment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_priorizacao_status'), ['priorizacao_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_search_run_id'), ['search_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospectcompany_user_email'), ['user_email'], unique=False)

    op.create_table('companycontact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cargo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senioridade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('perfil_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('perfil_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_confianca', sa.Integer(), nullable=True),
    sa.Column('email_buscado_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['prospectcompany.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companycontact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companycontact_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companycontact_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companycontact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companycontact_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_companycontact_company_id'))

    op.drop_table('companycontact')
    with op.batch_alter_table('prospectcompany', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospectcompany_user_email'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_search_run_id'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_priorizacao_status'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_enrichment_status'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_dominio'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_cnpj'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_approach_status'))
        batch_op.drop_index(batch_op.f('ix_prospectcompany_alerta_situacao'))

    op.drop_table('prospectcompany')
    with op.batch_alter_table('priorizacaorun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priorizacaorun_user_email'))
        batch_op.drop_index(batch_op.f('ix_priorizacaorun_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_priorizacaorun_search_run_id'))

    op.drop_table('priorizacaorun')
    with op.batch_alter_table('enrichmentrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichmentrun_user_email'))
        batch_op.drop_index(batch_op.f('ix_enrichmentrun_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_enrichmentrun_search_run_id'))

    op.drop_table('enrichmentrun')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reset_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('tokenusage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokenusage_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tokenusage_model'))

    op.drop_table('tokenusage')
    with op.batch_alter_table('searchrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searchrun_user_email'))
        batch_op.drop_index(batch_op.f('ix_searchrun_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_searchrun_pesquisa_id'))

    op.drop_table('searchrun')
    with op.batch_alter_table('searchconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searchconfig_tenant_id'))

    op.drop_table('searchconfig')
    op.drop_table('product')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_tenant_id'))

    op.drop_table('lead')
    with op.batch_alter_table('kipflowusage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kipflowusage_tenant_id'))

    op.drop_table('kipflowusage')
    with op.batch_alter_table('hunterusage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hunterusage_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_hunterusage_created_at'))
        batch_op.drop_index(batch_op.f('ix_hunterusage_contact_id'))
        batch_op.drop_index(batch_op.f('ix_hunterusage_account_slot'))

    op.drop_table('hunterusage')
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmessage_user_email'))
        batch_op.drop_index(batch_op.f('ix_chatmessage_tenant_id'))

    op.drop_table('chatmessage')
    with op.batch_alter_table('activitylog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activitylog_tenant_id'))

    op.drop_table('activitylog')
    with op.batch_alter_table('tokenpricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokenpricing_model'))

    op.drop_table('tokenpricing')
    op.drop_table('tenant')
    op.drop_table('integrationsetting')
    with op.batch_alter_table('hunteraccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hunteraccount_slot'))

    op.drop_table('hunteraccount')
    with op.batch_alter_table('agentmodelsetting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agentmodelsetting_agent_key'))

    op.drop_table('agentmodelsetting')
    # ### end Alembic commands ###
