"""config: contador de versao para deteccao de edicao concorrente

Revision ID: 7d300380d4f5
Revises: 0234eadb1702
Create Date: 2026-08-17 17:13:35.658332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7d300380d4f5'
down_revision: Union[str, Sequence[str], None] = '0234eadb1702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacaoconfig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('versao', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacaoconfig', schema=None) as batch_op:
        batch_op.drop_column('versao')

    # ### end Alembic commands ###
