"""agendador: batimento do tick

Revision ID: b2d99bb61726
Revises: 7d300380d4f5
Create Date: 2026-08-21 14:50:38.055772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b2d99bb61726'
down_revision: Union[str, Sequence[str], None] = '7d300380d4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacaoconfig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_tick_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_tick_resultado', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacaoconfig', schema=None) as batch_op:
        batch_op.drop_column('ultimo_tick_resultado')
        batch_op.drop_column('ultimo_tick_em')

    # ### end Alembic commands ###
