"""urgencia tratada

Revision ID: ebca27955309
Revises: 02ebad27db2f
Create Date: 2026-08-14 18:50:18.189463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ebca27955309'
down_revision: Union[str, Sequence[str], None] = '02ebad27db2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailclassificado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgencia_tratada_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_emailclassificado_urgencia_tratada_em'), ['urgencia_tratada_em'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailclassificado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emailclassificado_urgencia_tratada_em'))
        batch_op.drop_column('urgencia_tratada_em')

    # ### end Alembic commands ###
