"""prompt do classificador editavel

Revision ID: f658fb344a45
Revises: b2d99bb61726
Create Date: 2026-08-21 15:07:02.983775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f658fb344a45'
down_revision: Union[str, Sequence[str], None] = 'b2d99bb61726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promptagente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('chave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('atualizado_por_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chave', name='uq_prompt_tenant_chave')
    )
    with op.batch_alter_table('promptagente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promptagente_chave'), ['chave'], unique=False)
        batch_op.create_index(batch_op.f('ix_promptagente_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promptagente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promptagente_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_promptagente_chave'))

    op.drop_table('promptagente')
    # ### end Alembic commands ###
